### ISSUE TITLE
How much GPU Memory needed to finetune bigscience T0_3B Model?

### ISSUE THREAD

**Issue by rajab-mondal07** [bigscience-workshop/t-zero#12]
How much GPU Memory needed to finetune bigscience T0_3B Model? I tried to fine tune T0_3B model in 40 GB GPU Memory , Still getting below error:
RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 39.59 GiB total capacity; 36.36 GiB already allocated; 17.19 MiB free; 38.31 GiB reserved in total by PyTorch)

**Comment by VictorSanh** [comment]
hello @rajab-mondal07 
we indicated orders of magnitudes [here](https://github.com/bigscience-workshop/t-zero/tree/master/examples#distributed-training)!
