### ISSUE TITLE
mesh tensorflow checkpoints?

### ISSUE THREAD

**Issue by hamishivi** [bigscience-workshop/t-zero#25]
Hi, thanks for this great work!
Are you able to share mesh tensorflow checkpoints of the t0 models? It looks like you trained the models originally using the t5 mesh tensorflow library, so having these original checkpoints would be really useful for working with t0 using t5x (which I am trying to do).

**Comment by VictorSanh** [comment]
I emailed you @hamishivi :)

**Comment by ahmetustun** [comment]
Hi, great work! 
I was also looking for mesh tensorflow checkpoints of the T0 models. Would you be able to share them with me as well?  
I'd really appreciate it, thanks!
