### ISSUE TITLE
Instructions for fine-tuning a trained t-zero

### ISSUE THREAD

**Issue by louis030195** [bigscience-workshop/t-zero#8]
First, thanks for the great work!

Does it make sense to request instructions for fine-tuning a trained t-zero? That would be really great. If it is outside the scope of this repo, feel free to close this issue.

If yes, I would suggest providing the computing power required, thanks!

**Comment by VictorSanh** [comment]
hi @louis030195!
I think you will find this PR #3 interesting. it supports single task fine-tuning (including the few-shot case).

> If yes, I would suggest providing the computing power required, thanks!

If you mean, documenting how much resources (in number of GPUs for instance) are needed to fine-tune on a dataset of size XXX, yes we should do that!

**Comment by VictorSanh** [comment]
pr #3 is merged
